// <auto-generated />
namespace IntecBook.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correctiononnotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correctiononnotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201703261616405_Correction on notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
